name: Sanity Checks
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: "Linting"
        run: nix develop --command pre-commit run -a
      - name: Test
        run: nix develop --command poetry run pytest --cov=dataperro .
  build-test:
    name: "Build wheel"
    env:
      IMAGE_NAME: ${{ github.repository }}
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build wheel
        run: nix develop --command poetry build

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{env.IMAGE_NAME}}
          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            type=raw,value=${{github.ref_name}}
            type=raw,value=latest

      - name: Docker Build
        uses: docker/build-push-action@v5
        with:
          file: containers/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
